### ISSUE TITLE
Prepare a recap questionnaire

### ISSUE THREAD

**Issue by NelleV** [docathon/docathon#12]
To get feedback on our event.

**Comment by Carreau** [comment]
At the MSDSE event they used https://pollev.com/ to have people vote live from their phone. 

We can do that on the last day, and add a QR code / tinyurl for people quickly access it.

**Comment by choldgraf** [comment]
Pinging this again since we should start thinking about it. That's a cool idea @Carreau ...we can play around with some ideas for questions to ask on the last day, depending on how many folks are there in person.
