### ISSUE TITLE
Set up the infrastructure to get basic stats on project participating.

### ISSUE THREAD

**Issue by NelleV** [docathon/docathon#13]
NOTE: The scripts for this can be found in the `src` directory, as well as a part of the `watchtower` repository.

Right now, we plan on using

- [x] Google form used to register a project.
- [x] Nelle’s hacky script to find documentation related commits + cron job to produce the image.

**Comment by choldgraf** [comment]
These sound good to me. Where are you on this one? Do we have a prototype working yet? I think this is second-tier importance right now, after finalizing the website and making an announcement :)

**Comment by choldgraf** [comment]
pinging @NelleV to see where we are with the github stats tool. LMK if this is something other people could help out with, and where would be a useful place to put some time / effort

**Comment by NelleV** [comment]
Sprinting this saturday, from 9am to 1pm at Algorithms.
Anyone interested in helping me out either at the coffee shop or remotely, I'll be on our slack channel: https://docathon.herokuapp.com/
