### ISSUE TITLE
Tutorials for the first day

### ISSUE THREAD

**Issue by choldgraf** [docathon/docathon#26]
Here's a (growing) list of ideas for tutorials to cover during the docathon. Give some thoughts in the comments below and I'll add to the list.

[Here's a link](https://docs.google.com/spreadsheets/d/1BVzUiNUAWksf8l0lJ3WrtgY-DuGrGmJo54cdSkummlg/edit?usp=sharing) to the schedule for when the tutorials will occur

- [x] = confirmed

Time slots for the first day:
- [x] 30 min | Purposes and types of documentation (**Nelle**)
  * Make sure to find examples of these things in both Python and R
  * Categories of documentation (e.g., API, examples, tutorials)
  * Acceptable : short examples showing functionality
  * Better : examples + API, clear separation of these two
  * Best : many examples, full API coverage, high-level tutorials (nilearn, mne-python, sklearn)
- [x] 20 min | numpydoc (**Stefan**)
- [x] 20 min | sphinx gallery (**Chris**)
  * Is there a sphinx gallery kind of thing for R?
- [x] 20 min | RMarkdown / Bookdown / Documentation in R more generally - **Rebecca**
- [x] 20 min | Continuous Integration + a short promo for Hacker Within (**Matthias**)

THW on Tuesday: @Carreau + @choldgraf on zero to sphinx gallery + travis auto-build

Possible Topics
---
* How to create a description of high-level architecture of the project (e.g. describe objects/functions in relation to one another)
* High-level design document for a repository. Why does this thing exist? How can you think about it in the context of possible ways it could solve a problem. What other ways have people implemented the same thing?
* Create a template for a tutorial, define the general sections, heading, etc that is useful more generally

Other notes
---
* The guy from write the docs said he’d be happy to chat for a bit about their organization

**Comment by mrzv** [comment]
When do you plan the chat with the guy from write the docs?

**Comment by choldgraf** [comment]
Already chatted with him actually - it was a quick skype chat. Did you have any specific questions about the conversation?

**Comment by mrzv** [comment]
Ah, no, it sounded like the chat hadn't happened yet, so I was going to ask to join. No big deal.

**Comment by choldgraf** [comment]
I think he'd be willing to chat w/ the group at some point if we'd like, but our first chat was pretty quick

**Comment by NelleV** [comment]
Maybe you can do a quick summary during our next meeting.

**Comment by choldgraf** [comment]
yep - I'd like to chat about this as a group and agree on a list of topics...then we can figure out who actually knows how to teach these things :)

**Comment by choldgraf** [comment]
@stefanv this is where we're brainstorming ideas for projects. Once we have that finalized we can think of people who can present.

**Comment by rlbarter** [comment]
@Carreau @choldgraf  I can only do 11:40-12:00. Perhaps Matthias and I can switch? 

Another note: I'd suggest making sure that it is clear which tutorials are language-specific (and if so, which language), and which ones are more general. If people don't know about the specific tools, they probably won't know which ones are for python and which ones are for R

For example, I'd probably call mine either "_Documentation for R: RMarkdown, roxygen2 and bookdown_" or the more general "_Documentation for R_" (because most people won't realize that roxygen2 and bookdown are for R and probably won't have even heard of them unless they already do a lot of documentation in R).

**Comment by stefanv** [comment]
I'm not sure where this fits in, but would love a "plenary" by http://johnmacfarlane.net/

**Comment by choldgraf** [comment]
@rlbarter that sounds good to me - those placeholder names are just to cover the general idea of each talk, but feel free to professionalize as you like :)

I wonder if, rather than swapping, we can just push the talks a little bit later, as some people seem to be busy in the morning. We could have BIDS order a lunch for some folks perhaps?

@stefanv have you spoken with them before? That would be cool - do you know if they speak much?

**Comment by rlbarter** [comment]
@stefanv Something that might make that difficult is a statement on his home page: "I am on leave for the 2016–17 academic year at the Institut d’Études Avancées de Paris."

@choldgraf I would vote in favour of pushing the talks later! I'm free from 11:30am until around 3pm.

**Comment by choldgraf** [comment]
@rlbarter that is a good point haha.

for timing, let's discuss at the next meeting on thursday. @NelleV can you remember to bring this up? I'll add it to the meeting issue for now

**Comment by choldgraf** [comment]
Hey all - I removed the exact times we'd expect the talks to happen, and instead have an estimate for how long they'll take. All are at 20 minutes right now, but we could make that longer / shorter if we wanted.

There's also a link to the suggested schedule so we can use that for timing.

**Comment by rlbarter** [comment]
Hey everyone, is there a finalized timetable for the tutorials on the website anywhere?

**Comment by NelleV** [comment]
https://bids.github.io/docathon/pages/hosts/bids.html

**Comment by rlbarter** [comment]
Ah I see. Thanks!

**Comment by choldgraf** [comment]
@rlbarter are you good on your tutorial? Didn't get a chance to confirm with you at the meeting.

**Comment by rlbarter** [comment]
I sure am! I'm going to make a simple package, document it using roxygen then make a vignette and if there's time make a bookdown book :).

**Comment by Carreau** [comment]
@choldgraf do you want to include a "Closing remark" in the agenda ? You can shrink my slots by 2-3 minutes if necessary.

**Comment by choldgraf** [comment]
That's a good idea - I don't think we need to officially do this on the schedule but I can plan to give a quick overview of the coming days before lunch. Sounds good?

**Comment by Carreau** [comment]
Sounds good!
