### ISSUE TITLE
Add support for non-github commits

### ISSUE THREAD

**Issue by choldgraf** [docathon/docathon#78]
Right now we only support github, but there are lots of good projects hosted elsewhere too! We should figure out a way to add graphics support for those projects as well.

**Comment by willingc** [comment]
Hi @choldgraf. Libraries.io has done work very recently to incorporate GitLab and Bitbucket. It may be worth it to check there. Also, Grimoire Lab has built some related tools as well.

**Comment by choldgraf** [comment]
that's a good idea - the main trick would just be spending the time to figure out their API and credentialing, and then writing functions that would collect the responses such that they could co-exist with the github responses as well

**Comment by choldgraf** [comment]
I'm going to close this since this is probably better handled by our `watchtower` project: https://github.com/docathon/watchtower/issues/22
