### ISSUE TITLE
Effectless kwarg `groupby` in `count_doc_commits`

### ISSUE THREAD

**Issue by afvincent** [docathon/docathon#93]
The signature of `count_doc_commits` in `docathon/src/watchtower/calculate_project_commits.py` has a `groupby` keyword that does not seem to have any effect: from a simple Ctrl+F, it is not used/implemented anywhere in the function body. I guess that the original purpose was to use it to resample the dates per month or (week)day.

Currently it seems that there is some more or less implicit grouping by day from what I can read in b7cd730, *but I am not a Pandas user at all so I may be totally wrong here*.

**Comment by choldgraf** [comment]
Yep - I believe that you are correct! This was a carryover from a previous version of the site. Been spending the last few days fixing bigger bugs but I'll try and clean up this code as much as I can soon :) thanks for pointing it out!
