### ISSUE TITLE
Fix travis for the new host

### ISSUE THREAD

**Issue by choldgraf** [docathon/docathon#99]
I (somewhat too quickly) moved the docathon repo to live under the "docathon" org instead of BIDS. Now Travis is unhappy w/ the keys etc:

https://travis-ci.org/docathon/docathon

@Carreau could you help debug this?

**Comment by Carreau** [comment]
on it.

**Comment by Carreau** [comment]
Shall I deploy on BIDS.github.io ? Or docathon.github.io

**Comment by Carreau** [comment]
nevermind answerd my own question

**Comment by Carreau** [comment]
ok, resetup the deploy key, it works. 

I'm searching through files to replace bids.github.io by docathon.github.io.

**Comment by Carreau** [comment]
BTW, the images are the same for all blogposts.

**Comment by choldgraf** [comment]
thanks! re: blogposts, yeah, I made the mistake of just linking to the pages on the site, which I then realized are updated automatically :P 

In the future I think I'll post images to a github issue, and then link there

**Comment by Carreau** [comment]
Ok, things should work now.

**Comment by Carreau** [comment]
Gentleman Parrot

**Comment by choldgraf** [comment]
don't forget you can embed partyparrot in github with a markdown link :)

![](http://cultofthepartyparrot.com/parrots/hd/gentlemanparrot.gif)

#importantlifeskills

**Comment by Carreau** [comment]
Yeah, I just clicked too fast.

**Comment by choldgraf** [comment]
also I love the fact that partyparrots are in HD now

**Comment by choldgraf** [comment]
also, closing this issue before it devolves any further ;-)
